apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-modsecurity-15
  namespace: camelot
  selfLink: /api/v1/namespaces/camelot/replicationcontrollers/nginx-modsecurity-15
  uid: 32b059c6-aaba-11e7-add3-fa163efa9f1c
  resourceVersion: '4412077'
  generation: 3
  creationTimestamp: '2017-10-06T17:17:14Z'
  labels:
    app: nginx-modsecurity
    openshift.io/deployment-config.name: nginx-modsecurity
  annotations:
    openshift.io/deployer-pod.name: nginx-modsecurity-15-deploy
    openshift.io/deployment-config.latest-version: '15'
    openshift.io/deployment-config.name: nginx-modsecurity
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: ''
    openshift.io/deployment.status-reason: config change
    openshift.io/encoded-deployment-config: >
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"nginx-modsecurity","namespace":"camelot","selfLink":"/oapi/v1/namespaces/camelot/deploymentconfigs/nginx-modsecurity","uid":"584280bb-a9cd-11e7-add3-fa163efa9f1c","resourceVersion":"3955851","generation":30,"creationTimestamp":"2017-10-05T13:01:47Z","labels":{"app":"nginx-modsecurity"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["nginx-modsecurity"],"from":{"kind":"ImageStreamTag","namespace":"openshift","name":"nginx-modsecurity:latest"},"lastTriggeredImage":"docker.io/nodeintegration/nginx-modsecurity@sha256:629cb9a0b9c360962a53533f3d7631a83d13113b54e094174aa7efe2627775b7"}}],"replicas":1,"test":false,"selector":{"app":"nginx-modsecurity","deploymentconfig":"nginx-modsecurity"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx-modsecurity","deploymentconfig":"nginx-modsecurity"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"volumes":[{"name":"volume-ltvog","configMap":{"name":"nginx-config","items":[{"key":"default.conf","path":"default.conf"}],"defaultMode":420}}],"containers":[{"name":"nginx-modsecurity","image":"docker.io/nodeintegration/nginx-modsecurity@sha256:629cb9a0b9c360962a53533f3d7631a83d13113b54e094174aa7efe2627775b7","ports":[{"containerPort":80,"protocol":"TCP"},{"containerPort":443,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"volume-ltvog","mountPath":"/etc/nginx/conf.d/default.conf","subPath":"default.conf"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"useroot","serviceAccount":"useroot","securityContext":{}}}},"status":{"latestVersion":15,"observedGeneration":29,"replicas":2,"updatedReplicas":1,"availableReplicas":1,"unavailableReplicas":1,"details":{"message":"config
      change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2017-10-06T16:50:26Z","lastTransitionTime":"2017-10-06T16:50:26Z","message":"Deployment
      config has minimum
      availability."},{"type":"Progressing","status":"True","lastUpdateTime":"2017-10-06T17:12:51Z","lastTransitionTime":"2017-10-06T17:12:51Z","reason":"ReplicationControllerUpdated","message":"replication
      controller \"nginx-modsecurity-14\" is progressing"}],"readyReplicas":1}}
spec:
  replicas: 0
  selector:
    app: nginx-modsecurity
    deployment: nginx-modsecurity-15
    deploymentconfig: nginx-modsecurity
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-modsecurity
        deployment: nginx-modsecurity-15
        deploymentconfig: nginx-modsecurity
      annotations:
        openshift.io/deployment-config.latest-version: '15'
        openshift.io/deployment-config.name: nginx-modsecurity
        openshift.io/deployment.name: nginx-modsecurity-15
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: volume-ltvog
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
            defaultMode: 420
      containers:
        - name: nginx-modsecurity
          image: >-
            docker.io/nodeintegration/nginx-modsecurity@sha256:629cb9a0b9c360962a53533f3d7631a83d13113b54e094174aa7efe2627775b7
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: volume-ltvog
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: useroot
      serviceAccount: useroot
      securityContext: {}
status:
  replicas: 0
  observedGeneration: 3
