swagger: '2.0'
info:
  version: 2.0.0
  title: 3Scale CICD API
  description: 3Scale CICD API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: 3Scalers
    email: sgutierr@redhat.com
    url: 'http://sms.3scale.net'
  license:
    name: MIT
    url: 'https://github.com/sgutierr/cicd.git'
basePath: /
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  '/one-environment/config-connection':
    # binds a127 app logic to a route
    x-swagger-router-controller: cicd_controller  
    post:
      description: Config 3scale Connection
      operationId: configconnection
      parameters:
       - name: Credentials
         in: body
         description: id_subdomain
         required: true
         schema:
           $ref:  '#/definitions/Credentials'
      responses:
        '200':
          description: 3Scale connection configured 
          schema:
            title: Created
            properties:
              message:
                type: string
        '403':
          description: Configuration failed
          schema:
            $ref: '#/definitions/AuthenticationFailed'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/one-environment/new-service':
    x-swagger-router-controller: cicd_controller
    post:
      description: New 3scale Service
      operationId: createservice
      parameters:
        - name: Service
          in: body
          description: Service name
          required: true
          schema:
           $ref:  '#/definitions/ServiceName'
      responses:
        '200':
          description: 3scale service created
          schema:
            $ref: '#/definitions/ServiceStatus'
        '403':
          description: Authentication failed
          schema:
            $ref: '#/definitions/AuthenticationFailed'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/one-environment/import-demo-service':
      # binds a127 app logic to a route
    x-swagger-router-controller: cicd_controller
    post:
      description: Import demo service
      operationId: importservicedemo
      parameters:
        - name: Import
          in: body
          description: Importing a service
          required: true
          schema:
           $ref:  '#/definitions/ImportService'          
      responses:
        '200':
          description: Service imported
          schema:
            $ref: '#/definitions/ServiceStatus'
        '403':
          description: Authentication failed
          schema:
            $ref: '#/definitions/AuthenticationFailed'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/one-environment/test-service':
    x-swagger-router-controller: cicd_controller
    post:
      description: Testing a service 
      operationId: testingservice
      parameters:
        - name: TestService
          in: body
          description: Service Name
          required: true
          schema:
           $ref:  '#/definitions/TestService'          
      responses:
        '200':
          description: Test service in staging API gateway
          schema:
            $ref: '#/definitions/ServiceStatus'
        '403':
          description: Authentication failed
          schema:
            $ref: '#/definitions/AuthenticationFailed'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/one-environment/promotion-prod':
    x-swagger-router-controller: cicd_controller
    post:
      description: Promoting service to production gateways
      operationId: promotion_to_production
      parameters:
        - name: Service
          in: body
          description: service_name
          required: true
          schema:
           $ref:  '#/definitions/ServiceName'   
      responses:
        '200':
          description: Service promoted
          schema:
            $ref: '#/definitions/ServiceStatus'
        '403':
          description: Authentication failed
          schema:
            $ref: '#/definitions/AuthenticationFailed'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/two-environments/copy-service':
    x-swagger-router-controller: cicd_controller
    post:
      description: Copy service between environments
      operationId: copy_service
      parameters:
        - name: CopyService
          in: body
          description: copy_parameters
          required: true
          schema:
           $ref:  '#/definitions/CopyUpdate'   
      responses:
        '200':
          description: Service configuration copied
          schema:
            $ref: '#/definitions/ServiceStatus'
        '403':
          description: Authentication failed
          schema:
            $ref: '#/definitions/AuthenticationFailed'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/two-environments/update-service':
      # binds a127 app logic to a route
    x-swagger-router-controller: cicd_controller
    post:
      description: Update service between environments
      operationId: update_service
      parameters:
        - name: UpdateService
          in: body
          description: update_parameters
          required: true
          schema:
           $ref:  '#/definitions/CopyUpdate'   
      responses:
        '200':
          description: Service updated
          schema:
            $ref: '#/definitions/ServiceStatus'
        '403':
          description: Authentication failed
          schema:
            $ref: '#/definitions/AuthenticationFailed'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  ImportService:
    type: object
    required:
      - name
      - access_token
      - apim
    properties:
      name:
        type: string
      access_token:
        type: string
      apim:
        type: string
      swaggerDef:
        type: string          
  ServiceName:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      version:
        type: string
  TestService:
    type: object
    required:
      - name
      - environment
    properties:
      name:
        type: string
      environment:
        type: string
        enum:
          - sandbox
          - production        
      endpoint:
        type: string
  Credentials:
    type: object
    required:
      - subdomain
      - access_token
      - wildcard_domain
    properties:
      subdomain:
        type: string
      access_token:
        type: string
      wildcard_domain:
        type: string        
  CopyUpdate:
    type: object
    required:
      - id_source
      - id_dest
      - source
      - destination
    properties:
      id_source:
        type: string
      id_dest:
        type: string
      source:
        type: string        
      destination:
        type: string        
      name:
        type: string        
  ServiceStatus:
    required:
      - message
    properties:
      message:
        type: string
  AuthenticationFailed:
    type: object
  Error:
    type: object
